live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#272822"
blue = "#ae81ff"
cyan = "#66d9ef"
green = "#a6e22e"
magenta = "#fe558a"
red = "#f92672"
white = "#f8f8f0"
yellow = "#fd971f"

[colors.cursor]
cursor = "CellForeground"
text = "#272822"

[colors.normal]
black = "#272822"
blue = "#ae81ff"
cyan = "#66d9ef"
green = "#a6e22e"
magenta = "#fe558a"
red = "#f92672"
white = "#f8f8f0"
yellow = "#fd971f"

[colors.primary]
background = "#000000"
bright_foreground = "#FFFFFF"
foreground = "#f8f8f2"

[cursor.style]
blinking = "On"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "JetBrains Mono"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[window]
opacity = 0.9
