# https://github.com/akiyosi/goneovim/wiki/Usage#configuration
[Editor]
BorderlessWindow = true
HideTitlebar = true
FontFamily = "JetBrainsMono NFM"
FontSize = 18
DisableLigatures = false
Clipboard = true
ModeEnablingIME = ["insert"]
GinitVim = '''
cd $HOME
'''
#SmoothScroll = true
